### ISSUE TITLE
 Can I get 3D bounding box around objects in point cloud? Need it for dimension analysis

### ISSUE THREAD

**Issue by ayaan-mphasis** [Pointcept/SegmentAnything3D#20]

**Comment by BKINGING** [comment]
Excuse me, scannetv2 dataset is too large, do we need to download it all? Or just download these four?
python 1.py -o scannet/ --type _vh_clean_2.ply
python 1.py -o scannet/ --type _vh_clean_2.labels.ply
python 1.py -o scannet/ --type _vh_clean_2.0.010000.segs.json
python 1.py -o scannet/ --type .aggregation.json

**Comment by BKINGING** [comment]
Excuse me,Do you have any questions about this step? Could you take a look for me? Is it the dataset? I only got fourpython 1.py -o scannet/ --type _vh_clean_2.ply
python 1.py -o scannet/ --type _vh_clean_2.labels.ply
python 1.py -o scannet/ --type _vh_clean_2.0.010000.segs.json
python 1.py -o scannet/ --type .aggregation.json.

python scannet-preprocess/prepare_2d_data/prepare_2d_data.py --scannet_path dataout/train --output_path data/scannetv2_images --export_la
bel_images
Namespace(export_label_images=True, frame_skip=20, label_map_file='D:\Desktop\dianyun\SegmentAnything3D-main\data\scannetv2\scannetv2-labels.combined.tsv', label_type='label-filt
', output_image_height=240, output_image_width=320, output_path='data/scannetv2_images', scannet_path='dataout/train')
Traceback (most recent call last):
File "scannet-preprocess/prepare_2d_data/prepare_2d_data.py", line 118, in
main()
File "scannet-preprocess/prepare_2d_data/prepare_2d_data.py", line 71, in main
label_map = util.read_label_mapping(opt.label_map_file, label_from='id', label_to='nyu40id')
File "D:\Desktop\dianyun\SegmentAnything3D-main\scannet-preprocess\prepare_2d_data\util.py", line 42, in read_label_mapping
if represents_int(mapping.keys()[0]):
TypeError: 'dict_keys' object is not subscriptable

**Comment by ayaan-mphasis** [comment]
Can you please suggest on this. Thanks!
