### ISSUE TITLE
Error while running libs\pointops\setup.py

### ISSUE THREAD

**Issue by omrastogi** [Pointcept/SegmentAnything3D#39]
When running the setup.py I am getting the following error:

`Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    flag for flag in opt.split() if flag != '-Wstrict-prototypes'
AttributeError: 'NoneType' object has no attribute 'split'
`
On further investigation, it seems that "get_config_vars('OPT')" is returning 'None'. Now I can't find what 'OPT' configuration is expected. Please help me with this.

I am using Windows 11, Cuda 11.7, and Python 3.8 (as recommended)

**Comment by omrastogi** [comment]
Oh actually it worked by removing the following problems:

(opt,) = get_config_vars('OPT')

os.environ['OPT'] = " ".join(
    flag for flag in opt.split() if flag != '-Wstrict-prototypes'
)

**Comment by ImtheDM** [comment]
Hey, I am getting the same error:
```
File "setup.py", line 8, in <module>
    flag for flag in opt.split() if flag != '-Wstrict-prototypes'
AttributeError: 'NoneType' object has no attribute 'split'
```
After removing the lines you mentioned in your second reply I am getting this:
```
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```
Can you please help me with this?
I am using Windows 10 and python - 3.8 and I have followed all the installation steps given in the readme

**Comment by ShivaKPuppala** [comment]
me/shivap/skp/p0/python=3.8/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/shivap/skp/p0/python=3.8/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
^[[Drunning bdist_egg
running egg_info
writing pointops.egg-info/PKG-INFO
writing dependency_links to pointops.egg-info/dependency_links.txt
writing requirements to pointops.egg-info/requires.txt
writing top-level names to pointops.egg-info/top_level.txt
reading manifest file 'pointops.egg-info/SOURCES.txt'
writing manifest file 'pointops.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying functions/attention.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/utils.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/subtraction.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/__init__.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/aggregation.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/sampling.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/interpolation.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/grouping.py -> build/lib.linux-x86_64-cpython-38/pointops
copying functions/query.py -> build/lib.linux-x86_64-cpython-38/pointops
running build_ext
/home/shivap/skp/p0/python=3.8/lib/python3.8/site-packages/torch/utils/cpp_extension.py:425: UserWarning: There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.1
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
building 'pointops._C' extension
Emitting ninja build file /home/shivap/skp/p0/s_SegmentAny3D/SegmentAnything3D/libs/pointops/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)..........






i am getting above error when running python setup.py install  ......  i have no experience writing project.toml file instead of using setup.py . Can anyone help me resolving this issue?

**Comment by rebfjyjy** [comment]
> me/shivap/skp/p0/python=3.8/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated. !!
> 
> ```
>     ********************************************************************************
>     Please avoid running ``setup.py`` directly.
>     Instead, use pypa/build, pypa/installer or other
>     standards-based tools.
> 
>     See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
>     ********************************************************************************
> ```
> 
> !! self.initialize_options() /home/shivap/skp/p0/python=3.8/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated. !!
> 
> ```
>     ********************************************************************************
>     Please avoid running ``setup.py`` and ``easy_install``.
>     Instead, use pypa/build, pypa/installer or other
>     standards-based tools.
> 
>     See https://github.com/pypa/setuptools/issues/917 for details.
>     ********************************************************************************
> ```
> 
> !! self.initialize_options() ^[[Drunning bdist_egg running egg_info writing pointops.egg-info/PKG-INFO writing dependency_links to pointops.egg-info/dependency_links.txt writing requirements to pointops.egg-info/requires.txt writing top-level names to pointops.egg-info/top_level.txt reading manifest file 'pointops.egg-info/SOURCES.txt' writing manifest file 'pointops.egg-info/SOURCES.txt' installing library code to build/bdist.linux-x86_64/egg running install_lib running build_py copying functions/attention.py -> build/lib.linux-x86_64-cpython-38/pointops copying functions/utils.py -> build/lib.linux-x86_64-cpython-38/pointops copying functions/subtraction.py -> build/lib.linux-x86_64-cpython-38/pointops copying functions/**init**.py -> build/lib.linux-x86_64-cpython-38/pointops copying functions/aggregation.py -> build/lib.linux-x86_64-cpython-38/pointops copying functions/sampling.py -> build/lib.linux-x86_64-cpython-38/pointops copying functions/interpolation.py -> build/lib.linux-x86_64-cpython-38/pointops copying functions/grouping.py -> build/lib.linux-x86_64-cpython-38/pointops copying functions/query.py -> build/lib.linux-x86_64-cpython-38/pointops running build_ext /home/shivap/skp/p0/python=3.8/lib/python3.8/site-packages/torch/utils/cpp_extension.py:425: UserWarning: There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.1 warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}') building 'pointops._C' extension Emitting ninja build file /home/shivap/skp/p0/s_SegmentAny3D/SegmentAnything3D/libs/pointops/build/temp.linux-x86_64-cpython-38/build.ninja... Compiling objects... Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)..........
> 
> i am getting above error when running python setup.py install ...... i have no experience writing project.toml file instead of using setup.py . Can anyone help me resolving this issue?

did you happen to solve the issue?
